# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true

# edit here to achieve your personal greatness
url: http://chiefcll.github.io/
baseurl: /
title: Chris Lorenzo - Fellow Lightning JS Developer for TV Apps at GCS in Philadelphia
author: Chris Lorenzo
description: Personal blog and resume
avatar: profile.jpg
#email: chiefcll@gmail.com
github: chiefcll # username
twitter: chiefcll
linkedin: chris-lorenzo-3323667
stackoverflow: users/9324642/chris-lorenzo #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
#google_analytics: UA-69391421-1

# needed for travis-ci build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
